name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: debug
    defaults:
      run:
        working-directory: ./SmartCity

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run ktlint
        run: ./gradlew ktlintCheck
      - name: Run tests
        run: ./gradlew testDebugUnitTest
      - name: Build App debug
        run: ./gradlew :app:assembleDebug :app:assembleDebugUnitTest
